In [83]:
import numpy as np

array([1, 2, 3])

In [89]:
#creer un tableau de 1 dimension

ArrayBadInitilized = np.array([1,2,3]) #if I want to have an array initialized with elments 1,2,3

ArrayBadInitilized #array([1, 2, 3])
ArrayBadInitilized.ndim # 1
ArrayBadInitilized.shape # (3,)

# good initialisation 
vector = np.ones(3,) #array([1., 1., 1.])


#tabeleau 3 ligne et 1 columns avec bonne initialisation

A= np.zeros((3, 1)) #A.zeros(shape) avec shape est un tuple 3 = # lines and 1 = #columns
A
#array([[0.],
#       [0.],
#       [0.]])

A.shape #(3, 1)

(3,)

In [82]:

#Autres exemples
B= np.zeros((3,2)) 
B # array([[0., 0.], [0., 0.], [0., 0.]])

type(B) # numpy.ndarray
B.ndim #2
B.shape # (3,2)
type(B.shape) #tuple

C = np.ones((2,2))
C # array([[1., 1.], [1., 1.]])

D = np.full((2,3), 7)
D # array([[7, 7, 7], [7, 7, 7]])

EmptyArray = np.empty((2,3))
EmptyArray # same thig as np.zeros(...)

MatriceIdendity = np.eye(3)
MatriceIdendity
# array([[1., 0., 0.],
#       [0., 1., 0.],
#       [0., 0., 1.]])

A

array([[0.],
       [0.],
       [0.]])

In [69]:
#https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html

Matrice = np.random.randn(3,4) #Return a sample (or samples) from the “standard normal” distribution.
Matrice
#array([[-1.09586204, -1.08776574, -0.30517005, -0.47374837],
#       [-0.20059454,  0.35519677,  0.68951772,  0.41058968],
#       [-0.56497844,  0.59939069, -0.16293631,  1.6002145 ]])

type(Matrice) #numpy.ndarray

np.random.seed(15)
MatriceFixe = np.random.randn(2,3)
MatriceFixe # tjrs result: array([[-0.31232848,  0.33928471, -0.15590853], [-0.50178967,  0.23556889, -1.76360526]])

array([[-1.09586204, -1.08776574, -0.30517005, -0.47374837],
       [-0.20059454,  0.35519677,  0.68951772,  0.41058968],
       [-0.56497844,  0.59939069, -0.16293631,  1.6002145 ]])

In [29]:
#constructeur np.linspace(debut, fin, quantite)
A = np.linspace(0, 10, 5) #return un tableau qui contient 5 elemts entre 0 et 10
A #array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#constructeur np.arange(debut, fin, pas)
B = np.arange(0, 10, 3)
B # array([0, 3, 6 , 9 ])

array([0, 3, 6, 9])

In [40]:
# optional param dtype

FloatMatrice = np.linspace(0, 10 , 20,  dtype=np.float16)
FloatMatrice
#array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
 #       3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
  #      7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
   #    dtype=float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [49]:
# Manipulations
#Assembler 2 tableaux avec hstack (horisontal stack) et vstack (vertical stack)

A = np.zeros((3,2))
B = np.ones((3,2))

C = np.hstack((A,B)) 
# C = np.concatenate((A,B), axis=1) donne la meme chose

#A
#array([[0., 0.],
#       [0., 0.],
#       [0., 0.]])

B
#array([[1., 1.],
#       [1., 1.],
#       [1., 1.]])

C
#array([[0., 0., 1., 1.],
#       [0., 0., 1., 1.],
#       [0., 0., 1., 1.]])

D = np.vstack((A,B))
#D = np.concatenate((A,B), axis=0) donne la meme chose
D
#array([[0., 0.],
#       [0., 0.],
#       [0., 0.],
#       [1., 1.],
#       [1., 1.],
#       [1., 1.]])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
#reshape
A = np.ones((6,2)) # 6*2 = 12
A
#array([[1., 1.],
#       [1., 1.],
#       [1., 1.],
#       [1., 1.],
#       [1., 1.],
#       [1., 1.]])

A = A.reshape((3, 4)) # 3*4 = 12
A
#array([[1., 1., 1., 1.],
#       [1., 1., 1., 1.],
#       [1., 1., 1., 1.]])

# use reshape to correcte shape
#let be:
matrix = np.array([1,2,3])
matrix.shape #  (3,) (cas vector: 1 dimension avec 3 columns) or souvent le faite d'avoir un vide apres le 3 
             # est mauvais pour les calcul. 
             # On aimerait par ex avoir (3,1)
matrix = matrix.reshape((matrix.shape[0], 1))
matrix.shape #(3, 1)

#si on veut eliminer le 1
matrix = matrix.squeeze()
matrix.shape #(3,)

(3,)

In [65]:
#Methode ravel() pour aplatir un tableau 
A = np.zeros((2,2))
A 
#array([[0., 0.],
#       [0., 0.]])

A.ravel() # array([0., 0., 0., 0.])
A.ravel().shape # (4,)

(4,)

In [80]:
#Exercice

def initialisation(m, n):
    # m : # de lines
    # n : # de columns
    # return une matrice aleatoire (m, n+1)
    # avec une  colomun biais ('remplie de 1') toute a droite
    
    X = np.random.randn(m, n)
    X = np.concatenate((X, np.ones((X.shape[0], 1))), axis = 1) #array([[1.],
                                                                #       [1.],
                                                                #       [1.]])
    return X

A = initialisation(3, 4)
A


array([[ 1.21504155, -0.66751649, -0.27250578,  1.41677448,  1.        ],
       [-0.78260896, -0.2503207 , -0.30831446,  1.72968803,  1.        ],
       [ 1.97827237,  0.21968803,  1.89481985, -1.36809944,  1.        ]])