In [3]:
import numpy as np

#some simples maths method

A = np.random.randint(0,10, [2,3])
A
# [[5 0 0]
# [9 5 2]]
A.sum(axis=0) #[14  5  2]
A.sum(axis=1) #[ 5 16]
A.cumsum(axis=0) #cumsum :  [[ 5  0  0] [14  5  2]]
A.prod(axis=0) #prod :  [45  0  0]
A.cumprod(axis=0) #cumprod :  [[ 5  0  0] [45  0  0]]
A.min(axis=0) #[5, 0, 0] 5 < 9 , 0 < 5 ..ect
A.argmin(axis=0) # argmin :  [0 0 0] axe sur lequel se trouve le min. 5, 0, 0 position axe 0, 9 5 2 axe 1  
                                     # 5 < 9 et est sur l<axe 0, 0 < 5 et est a la position 0 (voir doc word)
A.sort(axis=0) #None
A.argsort(axis=0) #argsort :  [[0 0 0] [1 1 1]]


#e.g use somes routines maths : https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html
np.exp(A)


array([[7.38905610e+00, 4.03428793e+02, 1.09663316e+03],
       [8.10308393e+03, 1.09663316e+03, 2.98095799e+03]])

In [24]:
#Statistiques
A.min()
A.argmin()
A.mean()
A.var()
A.std() # ecart-type
#...etc

# somes routies stats: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html
np.corrcoef(A) # return une correlation entre les lignes d'une matrice (voir doc word)
               # array([[ 1.        , -0.24019223],
               #       [-0.24019223,  1.        ]])


# very used in stats
np.random.seed(15)
A2 = np.random.randint(0, 10, [3, 3])
A2
#array([[8, 5, 5],
#       [7, 0, 7],
#       [5, 6, 1]])

values, counts = np.unique(A2, return_counts=True) # return 1- tableau of different keys in A. 2- number of occurrance of each keys
                                                   #values = [0, 1, 5, 6, 7, 8] 
                                                   #counts = [1, 1, 3, 1, 2, 1]
counts.argsort() # [0, 1, 3, 5, 4, 2]  indexs qui permettent de trier counts

values[counts.argsort()] # [0, 1, 6, 8, 7, 5] values sont triés du nombre ayant le moins d'occurrence au plus ...
                         # on injecte les index qui permet de trier counts dans values, ce qui va retrier values\
                        #le nombre qui ressort le plus souvent est le 5 ensuite le 7 ensuite le 8 ...le moins souvent est 0
        
for i,j in zip(values[counts.argsort()], counts[counts.argsort()]) :
    print(f'value {i} apparait {j} fois')

#value 0 apparait 1 fois
#value 1 apparait 1 fois
#value 6 apparait 1 fois
#value 8 apparait 1 fois
#value 7 apparait 2 fois
#value 5 apparait 3 fois

# NAN correction

M = np.random.randn(5, 5)
M[2,2] = np.nan
M[2,4] = np.nan

#M.mean() --> error
np.nanmean(M) # 0.18132814194218835   Ignor Nan dans M

#number occurance in M
np.isnan(M)
#array([[False, False, False, False, False],
#       [False, False, False, False, False],
#       [False, False,  True, False, False],
#       [False, False, False, False, False],
#       [False, False, False, False, False]])

np.isnan(M).sum() # 2

#Se debarasser de NAN in an ndarry

M[np.isnan(M)] = 0
M # nan is replaced by 0

value 0 apparait 1 fois
value 1 apparait 1 fois
value 6 apparait 1 fois
value 8 apparait 1 fois
value 7 apparait 2 fois
value 5 apparait 3 fois


array([[-0.90211904,  0.68914456,  3.02040653,  0.11974284, -0.043533  ],
       [ 0.27173717,  0.51831502,  0.83956746, -0.39302039,  0.28153659],
       [ 1.09628496, -0.46211821,  0.        , -0.21511962,  0.        ],
       [-1.55106048, -1.23004904, -1.45905095, -0.85248466,  1.30204023],
       [ 1.21835914,  0.35386569,  0.26696959,  1.0741792 ,  0.53570848]])

In [ ]:
#Linear Algebra (see vid)

In [30]:
#Exercice
#stanrdiser la matrice A sur chaque colonne (A-A barre/variance de A)
#chaque colonne doit avoir une moyenne 0 et un ecart type= 1

np.random.seed(0)
A = np.random.randint(0, 100, [10, 4])

A = (A - A.mean(axis=0)) / A.std(axis=0)
A

#proove
A.std(axis=0) # array([1., 1., 1., 1.])

array([1., 1., 1., 1.])